---
title: "PAVO Analysis"
output: html_notebook
author: Emily White
---

```{r}
#install.packages("pavo")
```

```{r}
library("pavo")
```

Step 1: Organization and Processing

```{r}
#create a data frame that includes frog IDs and path to directory with spec data

frog_dirs <- dir(file.path("C:/Users/emmid/Desktop/SpecData/"), recursive=TRUE, include.dirs=TRUE, pattern= "(^\\d{1,}\\w{0,1}$)|(^..\\d$)")

spec_dirs<- file.path("C:/Users/emmid/Desktop/SpecData", frog_dirs)

frog_IDs <- read.table(file.path("C:/Users/emmid/Desktop/SpecData/Frog_IDs.txt"), header = TRUE, stringsAsFactors=FALSE)

spec_dirs_IDs <- mutate(frog_IDs, path=spec_dirs)
spec_dirs_IDs
```


```{r}
#create a function to analyze spec data for each frog
    dorsum_summary_total <- data.frame()
    hindlimb_summary_total <- data.frame()
    forelimb_summary_total <- data.frame()


for (y in c(1:90)) 
{
  specs <- getspec(where=spec_dirs_IDs[y,2], ext='txt', lim=c(400,1041), subdir=TRUE, subdir.names=TRUE)
  frog_ID <- spec_dirs_IDs[y,1]
  #subset spec data for body region
  #combine spec data within region and take the average
  #apply LOESS smoothing, make neg values 0
  #plot spectral curve
  
  specs_dorsum <- na.omit(subset(specs, subset=c("a", "b", "c", "d", "e", "f", "p", "q")))
  count_dorsum <- (ncol(specs_dorsum)-1)
  dorsum_agg <- aggspec(specs_dorsum, by=count_dorsum, FUN="mean")
  dorsum_agg_smooth <- procspec(dorsum_agg, opt="smooth", fixneg="zero", span=0.15)
  dorsum_summary <- summary(dorsum_agg_smooth, subset = c("B2","S1Y", "S1R","H1"))
  dorsum_summary$Individual_ID <- frog_ID
  dorsum_summary_total <- rbind(dorsum_summary_total, dorsum_summary)
  
  specs_hindlimb <- na.omit(subset(specs, subset=c("g","h")))
  count_hindlimb <- (ncol(specs_hindlimb)-1)
  if (count_hindlimb == 2) 
  {
    specs_hindlimb <- aggspec(specs_hindlimb, by=2, FUN="mean")
  }
  if (count_hindlimb == 2 || count_hindlimb == 1)
  {
    hindlimb_agg_smooth <- procspec(specs_hindlimb, opt="smooth", fixneg="zero", span=0.15)
    hindlimb_summary <- summary(hindlimb_agg_smooth, subset = c("B2","S1Y", "S1R","H1"))
    hindlimb_summary$Individual_ID <- frog_ID
    hindlimb_summary_total <- rbind(hindlimb_summary_total, hindlimb_summary)
  }
  
  specs_forelimb <- na.omit(subset(specs, subset=c("n", "o")))
  count_forelimb <- (ncol(specs_forelimb)-1)
  if (count_forelimb == 2) 
  {
    specs_forelimb <- aggspec(specs_forelimb, by=2, FUN="mean")
  }
  if (count_forelimb == 2 || count_forelimb == 1)
  {
    forelimb_agg_smooth <- procspec(specs_forelimb, opt="smooth", fixneg="zero", span=0.15)
    forelimb_summary <- summary(forelimb_agg_smooth, subset = c("B2","S1Y", "S1R","H1"))
    forelimb_summary$Individual_ID <- frog_ID
    forelimb_summary_total <- rbind(forelimb_summary_total, forelimb_summary)
  }
}
```

```{r}
    dorsum_summary_total
    hindlimb_summary_total
    forelimb_summary_total
```

```{r}
individual_key <- read.csv("C:/Users/emmid/Desktop/SpecData/Individual_Key.csv")
individual_key
```


```{r}
pedigree_info <- read.csv("C:/Users/emmid/Desktop/Research/pedigree_info_new.csv", colClasses = "character")
pedigree_info
```

```{r}
ped_dorsum <- merge(pedigree_info, dorsum_summary_total, by.y="Individual_ID", no.dups=TRUE, all.x=TRUE)
ped_dorsum <- ped_dorsum[,c(2,1,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17)]
ped_dorsum

ped_forelimb <- merge(pedigree_info, forelimb_summary_total, by.y="Individual_ID", no.dups=TRUE, all.x=TRUE)
ped_forelimb <- ped_forelimb[,c(2,1,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17)]
ped_forelimb

ped_hindlimb <- merge(pedigree_info, hindlimb_summary_total, by.y="Individual_ID", no.dups=TRUE, all.x=TRUE)
ped_hindlimb <- ped_hindlimb[,c(2,1,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17)]
ped_hindlimb
```

Change IDs to numbers for easier Merlin analysis
```{r}
ped_dorsum_nums <- ped_dorsum
for (y in c(1:88))
{ped_dorsum_nums <- replace.value(ped_dorsum_nums, c("Individual_ID", "Parent_1", "Parent_2"), from=individual_key[y,1], to=individual_key[y,2])}
```

```{r}
ped_forelimb_nums <- ped_forelimb
for (y in c(1:88))
{ped_forelimb_nums <- replace.value(ped_forelimb_nums, c("Individual_ID", "Parent_1", "Parent_2"), from=individual_key[y,1], to=individual_key[y,2])}
```

```{r}
ped_hindlimb_nums <- ped_hindlimb
for (y in c(1:88))
{ped_hindlimb_nums <- replace.value(ped_hindlimb_nums, c("Individual_ID", "Parent_1", "Parent_2"), from=individual_key[y,1], to=individual_key[y,2])}
```

Separate ASIP ped file and save
```{r}
ped_dorsum_asip <- subset(ped_dorsum_nums, select=c(Fam:asip2, B2:H1))
ped_dorsum_asip

ped_forelimb_asip <- subset(ped_forelimb_nums, select=c(Fam:asip2, B2:H1))
ped_forelimb_asip

ped_hindlimb_asip <- subset(ped_hindlimb_nums, select=c(Fam:asip2, B2:H1))
ped_hindlimb_asip
```

```{r}
write.table(ped_dorsum_asip, file="C:/Users/emmid/Desktop/Spec_Results/Ped_Files/ped_dorsum_asip.txt", sep="\t", row.names = FALSE, na="x", col.names = FALSE, quote=FALSE)
write.table(ped_forelimb_asip, file="C:/Users/emmid/Desktop/Spec_Results/Ped_Files/ped_forelimb_asip.txt", sep="\t", row.names = FALSE, na="x", col.names = FALSE, quote=FALSE)
write.table(ped_hindlimb_asip, file="C:/Users/emmid/Desktop/Spec_Results/Ped_Files/ped_hindlimb_asip.txt", sep="\t", row.names = FALSE, na="x", col.names = FALSE, quote=FALSE)
```


Separate mc1r ped file and save
```{r}
ped_dorsum_mc1r <- subset(ped_dorsum_nums, select= c(Fam:Sex,mc1r1:mc1r2, B2:H1))
ped_dorsum_mc1r

ped_forelimb_mc1r <- subset(ped_forelimb_nums,select= c(Fam:Sex,mc1r1:mc1r2, B2:H1))
ped_forelimb_mc1r

ped_hindlimb_mc1r <- subset(ped_hindlimb_nums,select= c(Fam:Sex,mc1r1:mc1r2, B2:H1))
ped_hindlimb_mc1r
```

```{r}
write.table(ped_dorsum_mc1r, file="C:/Users/emmid/Desktop/Spec_Results/Ped_Files/ped_dorsum_mc1r.txt", sep="\t", row.names = FALSE, na="x", col.names = FALSE, quote=FALSE)
write.table(ped_forelimb_mc1r, file="C:/Users/emmid/Desktop/Spec_Results/Ped_Files/ped_forelimb_mc1r.txt", sep="\t", row.names = FALSE, na="x", col.names = FALSE, quote=FALSE)
write.table(ped_hindlimb_mc1r, file="C:/Users/emmid/Desktop/Spec_Results/Ped_Files/ped_hindlimb_mc1r.txt", sep="\t", row.names = FALSE, na="x", col.names = FALSE, quote=FALSE)
```


Separate bsn2 ped file and save
```{r}
ped_dorsum_bsn2 <- subset(ped_dorsum_nums, select= c(Fam:Sex,bsn2.1:bsn2.2, B2:H1))
ped_dorsum_bsn2

ped_forelimb_bsn2 <- subset(ped_forelimb_nums,select= c(Fam:Sex,bsn2.1:bsn2.2, B2:H1))
ped_forelimb_bsn2

ped_hindlimb_bsn2 <- subset(ped_hindlimb_nums,select= c(Fam:Sex,bsn2.1:bsn2.2, B2:H1))
ped_hindlimb_bsn2
```

```{r}
write.table(ped_dorsum_bsn2, file="C:/Users/emmid/Desktop/Spec_Results/Ped_Files/ped_dorsum_bsn2.txt", sep="\t", row.names = FALSE, na="x", col.names = FALSE, quote=FALSE)
write.table(ped_forelimb_bsn2, file="C:/Users/emmid/Desktop/Spec_Results/Ped_Files/ped_forelimb_bsn2.txt", sep="\t", row.names = FALSE, na="x", col.names = FALSE, quote=FALSE)
write.table(ped_hindlimb_bsn2, file="C:/Users/emmid/Desktop/Spec_Results/Ped_Files/ped_hindlimb_bsn2.txt", sep="\t", row.names = FALSE, na="x", col.names = FALSE, quote=FALSE)
```


separate retsat ped file and save
```{r}
ped_dorsum_retsat <- subset(ped_dorsum_nums, select= c(Fam:Sex,retsat1:retsat2, B2:H1))
ped_dorsum_retsat

ped_forelimb_retsat <- subset(ped_forelimb_nums, select= c(Fam:Sex,retsat1:retsat2, B2:H1))
ped_forelimb_retsat

ped_hindlimb_retsat <- subset(ped_hindlimb_nums, select= c(Fam:Sex,retsat1:retsat2, B2:H1))
ped_hindlimb_retsat
```

```{r}
write.table(ped_dorsum_retsat, file="C:/Users/emmid/Desktop/Spec_Results/Ped_Files/ped_dorsum_retsat.txt", sep="\t", row.names = FALSE, na="x", col.names = FALSE, quote=FALSE)
write.table(ped_forelimb_retsat, file="C:/Users/emmid/Desktop/Spec_Results/Ped_Files/ped_forelimb_retsat.txt", sep="\t", row.names = FALSE, na="x", col.names = FALSE, quote=FALSE)
write.table(ped_hindlimb_retsat, file="C:/Users/emmid/Desktop/Spec_Results/Ped_Files/ped_hindlimb_retsat.txt", sep="\t", row.names = FALSE, na="x", col.names = FALSE, quote=FALSE)
```




